#ifndef KEYBOARD_INCLUDED
#define KEYBOARD_INCLUDED


typedef enum {
	KEY_ESCAPE = 1,
	
	KEY_1, KEY_2, KEY_3, KEY_4, KEY_5, KEY_6, KEY_7, KEY_8, KEY_9, KEY_0, KEY_MINUS, KEY_EQUAL, KEY_BACKSPACE,
	KEY_TAB, KEY_Q, KEY_W, KEY_E, KEY_R, KEY_T, KEY_Y, KEY_U, KEY_I, KEY_O, KEY_P, KEY_OPEN_SQUARE_BRACKET, KEY_CLOSE_SQUARE_BRACKET, KEY_ENTER,
	KEY_LEFT_CONTROL, KEY_A, KEY_S, KEY_D, KEY_F, KEY_G, KEY_H, KEY_J, KEY_K, KEY_L, KEY_SEMICOLON, KEY_APOSTROPHE, KEY_BACKTICK,
	KEY_LEFT_SHIFT, KEY_BACKSLASH, KEY_Z, KEY_X, KEY_C, KEY_V, KEY_B, KEY_N, KEY_M, KEY_COMMA, KEY_DOT, KEY_SLASH, KEY_RIGHT_SHIFT,
	
	KEY_NUMPAD_MUL,
	KEY_LEFT_ALT,
	KEY_SPACE,
	
	KEY_CAPSLOCK,
	KEY_F1, KEY_F2, KEY_F3, KEY_F4, KEY_F5, KEY_F6, KEY_F7, KEY_F8, KEY_F9, KEY_F10,
	KEY_NUM_LOCK, KEY_SCROLL_LOCK,
	
	KEY_NUMPAD_7, KEY_NUMPAD_8, KEY_NUMPAD_9, KEY_NUMPAD_MINUS,
	KEY_NUMPAD_4, KEY_NUMPAD_5, KEY_NUMPAD_6, KEY_NUMPAD_PLUS,
	KEY_NUMPAD_1, KEY_NUMPAD_2, KEY_NUMPAD_3,
	KEY_NUMPAD_0, KEY_NUMPAD_DOT,
	
	KEY_F11 = 87,
	KEY_F12 = 88,




	KEY_NUMPAD_ENTER = 156,
	KEY_RIGHT_CONTROL = 157,
	KEY_PRINT_SCREEN2 = 170,
	KEY_NUMPAD_DIV = 181,
	KEY_PRINT_SCREEN = 183,
	KEY_RIGHT_ALT = 184,
	
	KEY_HOME = 199,
	KEY_ARROW_UP = 200,
	KEY_PAGE_UP = 201,
	KEY_ARROW_LEFT = 203,
	KEY_ARROW_RIGHT = 205,
	KEY_END = 207,
	KEY_ARROW_DOWN = 208,
	KEY_PAGE_DOWN = 209,
	KEY_INSERT = 210,
	KEY_DELETE = 211,
	
	KEY_OS = 219,
	KEY_CONTEXT_MENU = 221,
}
Key_Code;


typedef struct {
	Number32 (*read_key_state) ();
}
Keyboard_Interface;


#endif//KEYBOARD_INCLUDED